name: Publish to NuGet
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 5
      - name: publish on version change
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/InertiaAdapter/InertiaAdapter.csproj
          TAG_FORMAT: "*"
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
